name: "Main branch builds"
on:
  push:
    branches: main 

jobs:
  build:
    name: "Build artifacts"
    uses: ./.github/workflows/build_artifacts.yaml
    with:
      include_publishable_package: true
